export const pilar18Average = [
  { id: 1, average: 0 },
  { id: 2, average: 0 },
  { id: 3, average: 0 },
  { id: 4, average: 0 },
  { id: 5, average: 0 },
  { id: 6, average: 0 },
  { id: 7, average: 0 },
  { id: 8, average: 0 },
  { id: 9, average: 0 },
  { id: 10, average: 0 },
  { id: 11, average: 0 },
  { id: 12, average: 0 },
  { id: 13, average: 0 },
  { id: 14, average: 0 },
  { id: 15, average: 0 },
  { id: 16, average: 0 },
  { id: 17, average: 0 },
  { id: 18, average: 0 },
];
